// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: verify_code.proto
// Protobuf C++ Version: 6.33.1

#ifndef verify_5fcode_2eproto_2epb_2eh
#define verify_5fcode_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_verify_5fcode_2eproto

namespace google
{
namespace protobuf
{
namespace internal
{
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_verify_5fcode_2eproto
{
  static const ::uint32_t offsets[];
};
extern "C"
{
  extern const ::google::protobuf::internal::DescriptorTable descriptor_table_verify_5fcode_2eproto;
}  // extern "C"
namespace KBchulan
{
namespace ChatRoom
{
namespace VerifyCode
{
class VerifyCodeRequest;
struct VerifyCodeRequestDefaultTypeInternal;
extern VerifyCodeRequestDefaultTypeInternal _VerifyCodeRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull VerifyCodeRequest_class_data_;
class VerifyCodeResponse;
struct VerifyCodeResponseDefaultTypeInternal;
extern VerifyCodeResponseDefaultTypeInternal _VerifyCodeResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull VerifyCodeResponse_class_data_;
class VerifyCodeResponse_DataEntry_DoNotUse;
struct VerifyCodeResponse_DataEntry_DoNotUseDefaultTypeInternal;
extern VerifyCodeResponse_DataEntry_DoNotUseDefaultTypeInternal
    _VerifyCodeResponse_DataEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull VerifyCodeResponse_DataEntry_DoNotUse_class_data_;
}  // namespace VerifyCode
}  // namespace ChatRoom
}  // namespace KBchulan
namespace google
{
namespace protobuf
{
}  // namespace protobuf
}  // namespace google

namespace KBchulan
{
namespace ChatRoom
{
namespace VerifyCode
{

// ===================================================================

// -------------------------------------------------------------------

class VerifyCodeResponse_DataEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                                                    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                                                    ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
{
public:
  using SuperType = ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                                                           ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                                                           ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  VerifyCodeResponse_DataEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VerifyCodeResponse_DataEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit VerifyCodeResponse_DataEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance()
  {
    return &_VerifyCodeResponse_DataEntry_DoNotUse_default_instance_;
  }

  static constexpr auto InternalGenerateClassData_();

private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_verify_5fcode_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 74, 2> _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
                                              ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull VerifyCodeResponse_DataEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class VerifyCodeRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest) */ {
public:
  inline VerifyCodeRequest() : VerifyCodeRequest(nullptr)
  {
  }
  ~VerifyCodeRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VerifyCodeRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t)
  {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VerifyCodeRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VerifyCodeRequest(::google::protobuf::internal::ConstantInitialized);

  inline VerifyCodeRequest(const VerifyCodeRequest& from) : VerifyCodeRequest(nullptr, from)
  {
  }
  inline VerifyCodeRequest(VerifyCodeRequest&& from) noexcept : VerifyCodeRequest(nullptr, ::std::move(from))
  {
  }
  inline VerifyCodeRequest& operator=(const VerifyCodeRequest& from)
  {
    CopyFrom(from);
    return *this;
  }
  inline VerifyCodeRequest& operator=(VerifyCodeRequest&& from) noexcept
  {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena()))
    {
      InternalSwap(&from);
    }
    else
    {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
        ::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor()
  {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor()
  {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection()
  {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyCodeRequest& default_instance()
  {
    return *reinterpret_cast<const VerifyCodeRequest*>(&_VerifyCodeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VerifyCodeRequest& a, VerifyCodeRequest& b)
  {
    a.Swap(&b);
  }
  inline void Swap(VerifyCodeRequest* PROTOBUF_NONNULL other)
  {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena()))
    {
      InternalSwap(other);
    }
    else
    {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyCodeRequest* PROTOBUF_NONNULL other)
  {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyCodeRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const
  {
    return ::google::protobuf::Message::DefaultConstruct<VerifyCodeRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VerifyCodeRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VerifyCodeRequest& from)
  {
    VerifyCodeRequest::MergeImpl(*this, from);
  }

private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg);

public:
  bool IsInitialized() const
  {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
#if defined(PROTOBUF_CUSTOM_VTABLE)
private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL
  _InternalSerialize(const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
                     ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

public:
  ::size_t ByteSizeLong() const
  {
    return ByteSizeLong(*this);
  }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target, ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const
  {
    return _InternalSerialize(*this, target, stream);
  }
#else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL
  _InternalSerialize(::uint8_t* PROTOBUF_NONNULL target,
                     ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
#endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const
  {
    return _impl_._cached_size_.Get();
  }

private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VerifyCodeRequest* PROTOBUF_NONNULL other);

private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName()
  {
    return "KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest";
  }

  explicit VerifyCodeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  VerifyCodeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VerifyCodeRequest& from);
  VerifyCodeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, VerifyCodeRequest&& from) noexcept
      : VerifyCodeRequest(arena)
  {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
                                              ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int
  {
    kEmailFieldNumber = 1,
  };
  // string email = 1;
  void clear_email();
  const ::std::string& email() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_email(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_email();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_email();
  void set_allocated_email(::std::string* PROTOBUF_NULLABLE value);

private:
  const ::std::string& _internal_email() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_email(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_email();

public:
  // @@protoc_insertion_point(class_scope:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 60, 2> _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_
  {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
                          const VerifyCodeRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr email_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union
  {
    Impl_ _impl_;
  };
  friend struct ::TableStruct_verify_5fcode_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull VerifyCodeRequest_class_data_;
// -------------------------------------------------------------------

class VerifyCodeResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse) */ {
public:
  inline VerifyCodeResponse() : VerifyCodeResponse(nullptr)
  {
  }
  ~VerifyCodeResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VerifyCodeResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t)
  {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VerifyCodeResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VerifyCodeResponse(::google::protobuf::internal::ConstantInitialized);

  inline VerifyCodeResponse(const VerifyCodeResponse& from) : VerifyCodeResponse(nullptr, from)
  {
  }
  inline VerifyCodeResponse(VerifyCodeResponse&& from) noexcept : VerifyCodeResponse(nullptr, ::std::move(from))
  {
  }
  inline VerifyCodeResponse& operator=(const VerifyCodeResponse& from)
  {
    CopyFrom(from);
    return *this;
  }
  inline VerifyCodeResponse& operator=(VerifyCodeResponse&& from) noexcept
  {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena()))
    {
      InternalSwap(&from);
    }
    else
    {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
        ::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND
  {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor()
  {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor()
  {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection()
  {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyCodeResponse& default_instance()
  {
    return *reinterpret_cast<const VerifyCodeResponse*>(&_VerifyCodeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(VerifyCodeResponse& a, VerifyCodeResponse& b)
  {
    a.Swap(&b);
  }
  inline void Swap(VerifyCodeResponse* PROTOBUF_NONNULL other)
  {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena()))
    {
      InternalSwap(other);
    }
    else
    {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyCodeResponse* PROTOBUF_NONNULL other)
  {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyCodeResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const
  {
    return ::google::protobuf::Message::DefaultConstruct<VerifyCodeResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VerifyCodeResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VerifyCodeResponse& from)
  {
    VerifyCodeResponse::MergeImpl(*this, from);
  }

private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg);

public:
  bool IsInitialized() const
  {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
#if defined(PROTOBUF_CUSTOM_VTABLE)
private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL
  _InternalSerialize(const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
                     ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

public:
  ::size_t ByteSizeLong() const
  {
    return ByteSizeLong(*this);
  }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target, ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const
  {
    return _InternalSerialize(*this, target, stream);
  }
#else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL
  _InternalSerialize(::uint8_t* PROTOBUF_NONNULL target,
                     ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
#endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const
  {
    return _impl_._cached_size_.Get();
  }

private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VerifyCodeResponse* PROTOBUF_NONNULL other);

private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName()
  {
    return "KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse";
  }

  explicit VerifyCodeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  VerifyCodeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VerifyCodeResponse& from);
  VerifyCodeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, VerifyCodeResponse&& from) noexcept
      : VerifyCodeResponse(arena)
  {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
                                              ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int
  {
    kMessageFieldNumber = 2,
    kCodeFieldNumber = 1,
    kDataFieldNumber = 3,
  };
  // string message = 2;
  void clear_message();
  const ::std::string& message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_message();
  void set_allocated_message(::std::string* PROTOBUF_NULLABLE value);

private:
  const ::std::string& _internal_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_message();

public:
  // int32 code = 1;
  void clear_code();
  ::int32_t code() const;
  void set_code(::int32_t value);

private:
  ::int32_t _internal_code() const;
  void _internal_set_code(::int32_t value);

public:
  // map<string, string> data = 3;
  int data_size() const;

private:
  int _internal_data_size() const;

public:
  void clear_data();
  const ::google::protobuf::Map<::std::string, ::std::string>& data() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_data();

private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_data() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_data();

public:
  // @@protoc_insertion_point(class_scope:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 3, 1, 67, 2> _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_
  {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
                          const VerifyCodeResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::int32_t code_;
    ::google::protobuf::internal::MapField<VerifyCodeResponse_DataEntry_DoNotUse, ::std::string, ::std::string,
                                           ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                                           ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union
  {
    Impl_ _impl_;
  };
  friend struct ::TableStruct_verify_5fcode_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull VerifyCodeResponse_class_data_;

// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VerifyCodeRequest

// string email = 1;
inline void VerifyCodeRequest::clear_email()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& VerifyCodeRequest::email() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_get:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest.email)
  return _internal_email();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VerifyCodeRequest::set_email(Arg_&& arg, Args_... args)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.email_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest.email)
}
inline ::std::string* PROTOBUF_NONNULL VerifyCodeRequest::mutable_email() ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest.email)
  return _s;
}
inline const ::std::string& VerifyCodeRequest::_internal_email() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.email_.Get();
}
inline void VerifyCodeRequest::_internal_set_email(const ::std::string& value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VerifyCodeRequest::_internal_mutable_email()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.email_.Mutable(GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VerifyCodeRequest::release_email()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest.email)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U))
  {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.email_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString())
  {
    _impl_.email_.Set("", GetArena());
  }
  return released;
}
inline void VerifyCodeRequest::set_allocated_email(::std::string* PROTOBUF_NULLABLE value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr)
  {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  else
  {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.email_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.email_.IsDefault())
  {
    _impl_.email_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest.email)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// VerifyCodeResponse

// int32 code = 1;
inline void VerifyCodeResponse::clear_code()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int32_t VerifyCodeResponse::code() const
{
  // @@protoc_insertion_point(field_get:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.code)
  return _internal_code();
}
inline void VerifyCodeResponse::set_code(::int32_t value)
{
  _internal_set_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.code)
}
inline ::int32_t VerifyCodeResponse::_internal_code() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.code_;
}
inline void VerifyCodeResponse::_internal_set_code(::int32_t value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = value;
}

// string message = 2;
inline void VerifyCodeResponse::clear_message()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& VerifyCodeResponse::message() const ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_get:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VerifyCodeResponse::set_message(Arg_&& arg, Args_... args)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.message)
}
inline ::std::string* PROTOBUF_NONNULL VerifyCodeResponse::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.message)
  return _s;
}
inline const ::std::string& VerifyCodeResponse::_internal_message() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void VerifyCodeResponse::_internal_set_message(const ::std::string& value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VerifyCodeResponse::_internal_mutable_message()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable(GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VerifyCodeResponse::release_message()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.message)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U))
  {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString())
  {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void VerifyCodeResponse::set_allocated_message(::std::string* PROTOBUF_NULLABLE value)
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr)
  {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  else
  {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault())
  {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.message)
}

// map<string, string> data = 3;
inline int VerifyCodeResponse::_internal_data_size() const
{
  return _internal_data().size();
}
inline int VerifyCodeResponse::data_size() const
{
  return _internal_data_size();
}
inline void VerifyCodeResponse::clear_data()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& VerifyCodeResponse::_internal_data() const
{
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& VerifyCodeResponse::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  // @@protoc_insertion_point(field_map:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.data)
  return _internal_data();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL
VerifyCodeResponse::_internal_mutable_data()
{
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL VerifyCodeResponse::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_map:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.data)
  return _internal_mutable_data();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace VerifyCode
}  // namespace ChatRoom
}  // namespace KBchulan

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // verify_5fcode_2eproto_2epb_2eh
