// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: verify_code.proto
#ifndef GRPC_verify_5fcode_2eproto__INCLUDED
#define GRPC_verify_5fcode_2eproto__INCLUDED

#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/server_context.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

#include <functional>
#include <grpcpp/ports_def.inc>

#include "verify_code.pb.h"

namespace KBchulan
{
namespace ChatRoom
{
namespace VerifyCode
{

class VerifyCodeService final
{
public:
  static constexpr char const* service_full_name()
  {
    return "KBchulan.ChatRoom.VerifyCode.VerifyCodeService";
  }
  class StubInterface
  {
  public:
    virtual ~StubInterface()
    {
    }
    virtual ::grpc::Status VerifyCode(::grpc::ClientContext* context,
                                      const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                                      ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response) = 0;
    std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>>
    AsyncVerifyCode(::grpc::ClientContext* context, const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                    ::grpc::CompletionQueue* cq)
    {
      return std::unique_ptr<
          ::grpc::ClientAsyncResponseReaderInterface<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>>(
          AsyncVerifyCodeRaw(context, request, cq));
    }
    std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>>
    PrepareAsyncVerifyCode(::grpc::ClientContext* context,
                           const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                           ::grpc::CompletionQueue* cq)
    {
      return std::unique_ptr<
          ::grpc::ClientAsyncResponseReaderInterface<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>>(
          PrepareAsyncVerifyCodeRaw(context, request, cq));
    }
    class async_interface
    {
    public:
      virtual ~async_interface()
      {
      }
      virtual void VerifyCode(::grpc::ClientContext* context,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
                              ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response,
                              std::function<void(::grpc::Status)>) = 0;
      virtual void VerifyCode(::grpc::ClientContext* context,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
                              ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response,
                              ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async()
    {
      return nullptr;
    }
    class async_interface* experimental_async()
    {
      return async();
    }

  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>*
    AsyncVerifyCodeRaw(::grpc::ClientContext* context,
                       const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                       ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>*
    PrepareAsyncVerifyCodeRaw(::grpc::ClientContext* context,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                              ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface
  {
  public:
    Stub(const std::shared_ptr<::grpc::ChannelInterface>& channel,
         const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status VerifyCode(::grpc::ClientContext* context,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                              ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response) override;
    std::unique_ptr<::grpc::ClientAsyncResponseReader<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>>
    AsyncVerifyCode(::grpc::ClientContext* context, const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                    ::grpc::CompletionQueue* cq)
    {
      return std::unique_ptr<::grpc::ClientAsyncResponseReader<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>>(
          AsyncVerifyCodeRaw(context, request, cq));
    }
    std::unique_ptr<::grpc::ClientAsyncResponseReader<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>>
    PrepareAsyncVerifyCode(::grpc::ClientContext* context,
                           const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                           ::grpc::CompletionQueue* cq)
    {
      return std::unique_ptr<::grpc::ClientAsyncResponseReader<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>>(
          PrepareAsyncVerifyCodeRaw(context, request, cq));
    }
    class async final : public StubInterface::async_interface
    {
    public:
      void VerifyCode(::grpc::ClientContext* context,
                      const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
                      ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response,
                      std::function<void(::grpc::Status)>) override;
      void VerifyCode(::grpc::ClientContext* context,
                      const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
                      ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response,
                      ::grpc::ClientUnaryReactor* reactor) override;

    private:
      friend class Stub;
      explicit async(Stub* stub) : stub_(stub)
      {
      }
      Stub* stub()
      {
        return stub_;
      }
      Stub* stub_;
    };
    class async* async() override
    {
      return &async_stub_;
    }

  private:
    std::shared_ptr<::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>* AsyncVerifyCodeRaw(
        ::grpc::ClientContext* context, const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
        ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>* PrepareAsyncVerifyCodeRaw(
        ::grpc::ClientContext* context, const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
        ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_VerifyCode_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr<::grpc::ChannelInterface>& channel,
                                       const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service
  {
  public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status VerifyCode(::grpc::ServerContext* context,
                                      const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
                                      ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_VerifyCode : public BaseClass
  {
  private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/)
    {
    }

  public:
    WithAsyncMethod_VerifyCode()
    {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_VerifyCode() override
    {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* /*request*/,
                              ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* /*response*/) override
    {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyCode(
        ::grpc::ServerContext* context, ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
        ::grpc::ServerAsyncResponseWriter<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>* response,
        ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void* tag)
    {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_VerifyCode<Service> AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_VerifyCode : public BaseClass
  {
  private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/)
    {
    }

  public:
    WithCallbackMethod_VerifyCode()
    {
      ::grpc::Service::MarkMethodCallback(
          0, new ::grpc::internal::CallbackUnaryHandler<::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
                                                        ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>(
                 [this](::grpc::CallbackServerContext* context,
                        const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
                        ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response)
                 { return this->VerifyCode(context, request, response); }));
    }
    void SetMessageAllocatorFor_VerifyCode(
        ::grpc::MessageAllocator<::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
                                 ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>* allocator)
    {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler<::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
                                                         ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>*>(
          handler)
          ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_VerifyCode() override
    {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* /*request*/,
                              ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* /*response*/) override
    {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyCode(
        ::grpc::CallbackServerContext* /*context*/,
        const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* /*request*/,
        ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* /*response*/)
    {
      return nullptr;
    }
  };
  typedef WithCallbackMethod_VerifyCode<Service> CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_VerifyCode : public BaseClass
  {
  private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/)
    {
    }

  public:
    WithGenericMethod_VerifyCode()
    {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_VerifyCode() override
    {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* /*request*/,
                              ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* /*response*/) override
    {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_VerifyCode : public BaseClass
  {
  private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/)
    {
    }

  public:
    WithRawMethod_VerifyCode()
    {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_VerifyCode() override
    {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* /*request*/,
                              ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* /*response*/) override
    {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyCode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request,
                           ::grpc::ServerAsyncResponseWriter<::grpc::ByteBuffer>* response,
                           ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq,
                           void* tag)
    {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VerifyCode : public BaseClass
  {
  private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/)
    {
    }

  public:
    WithRawCallbackMethod_VerifyCode()
    {
      ::grpc::Service::MarkMethodRawCallback(
          0, new ::grpc::internal::CallbackUnaryHandler<::grpc::ByteBuffer, ::grpc::ByteBuffer>(
                 [this](::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request,
                        ::grpc::ByteBuffer* response) { return this->VerifyCode(context, request, response); }));
    }
    ~WithRawCallbackMethod_VerifyCode() override
    {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* /*request*/,
                              ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* /*response*/) override
    {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyCode(::grpc::CallbackServerContext* /*context*/,
                                                   const ::grpc::ByteBuffer* /*request*/,
                                                   ::grpc::ByteBuffer* /*response*/)
    {
      return nullptr;
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VerifyCode : public BaseClass
  {
  private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/)
    {
    }

  public:
    WithStreamedUnaryMethod_VerifyCode()
    {
      ::grpc::Service::MarkMethodStreamed(
          0, new ::grpc::internal::StreamedUnaryHandler<::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
                                                        ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>(
                 [this](::grpc::ServerContext* context,
                        ::grpc::ServerUnaryStreamer<::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
                                                    ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>* streamer)
                 { return this->StreamedVerifyCode(context, streamer); }));
    }
    ~WithStreamedUnaryMethod_VerifyCode() override
    {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VerifyCode(::grpc::ServerContext* /*context*/,
                              const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* /*request*/,
                              ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* /*response*/) override
    {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerifyCode(
        ::grpc::ServerContext* context,
        ::grpc::ServerUnaryStreamer<::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
                                    ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_VerifyCode<Service> StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_VerifyCode<Service> StreamedService;
};

}  // namespace VerifyCode
}  // namespace ChatRoom
}  // namespace KBchulan

#include <grpcpp/ports_undef.inc>
#endif  // GRPC_verify_5fcode_2eproto__INCLUDED
