// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: verify_code.proto
// Protobuf C++ Version: 6.33.1

#include "verify_code.pb.h"

#include <algorithm>
#include <type_traits>

#include "google/protobuf/descriptor.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/wire_format_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace KBchulan
{
namespace ChatRoom
{
namespace VerifyCode
{
template <typename>
PROTOBUF_CONSTEXPR VerifyCodeResponse_DataEntry_DoNotUse::VerifyCodeResponse_DataEntry_DoNotUse(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : VerifyCodeResponse_DataEntry_DoNotUse::MapEntry(VerifyCodeResponse_DataEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : VerifyCodeResponse_DataEntry_DoNotUse::MapEntry()
{
}
#endif  // PROTOBUF_CUSTOM_VTABLE
      struct VerifyCodeResponse_DataEntry_DoNotUseDefaultTypeInternal
{
  PROTOBUF_CONSTEXPR VerifyCodeResponse_DataEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{})
  {
  }
  ~VerifyCodeResponse_DataEntry_DoNotUseDefaultTypeInternal()
  {
  }
  union
  {
    VerifyCodeResponse_DataEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    VerifyCodeResponse_DataEntry_DoNotUseDefaultTypeInternal _VerifyCodeResponse_DataEntry_DoNotUse_default_instance_;

inline constexpr VerifyCodeRequest::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0}, email_(&::google::protobuf::internal::fixed_address_empty_string, ::_pbi::ConstantInitialized())
{
}

template <typename>
PROTOBUF_CONSTEXPR VerifyCodeRequest::VerifyCodeRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(VerifyCodeRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized())
{
}
struct VerifyCodeRequestDefaultTypeInternal
{
  PROTOBUF_CONSTEXPR VerifyCodeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{})
  {
  }
  ~VerifyCodeRequestDefaultTypeInternal()
  {
  }
  union
  {
    VerifyCodeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VerifyCodeRequestDefaultTypeInternal
    _VerifyCodeRequest_default_instance_;

inline constexpr VerifyCodeResponse::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0},
      message_(&::google::protobuf::internal::fixed_address_empty_string, ::_pbi::ConstantInitialized()),
      code_{0},
      data_{}
{
}

template <typename>
PROTOBUF_CONSTEXPR VerifyCodeResponse::VerifyCodeResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(VerifyCodeResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized())
{
}
struct VerifyCodeResponseDefaultTypeInternal
{
  PROTOBUF_CONSTEXPR VerifyCodeResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{})
  {
  }
  ~VerifyCodeResponseDefaultTypeInternal()
  {
  }
  union
  {
    VerifyCodeResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VerifyCodeResponseDefaultTypeInternal
    _VerifyCodeResponse_default_instance_;
}  // namespace VerifyCode
}  // namespace ChatRoom
}  // namespace KBchulan
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_verify_5fcode_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_verify_5fcode_2eproto = nullptr;
const ::uint32_t TableStruct_verify_5fcode_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
    0x081,  // bitmap
    PROTOBUF_FIELD_OFFSET(::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest, _impl_._has_bits_),
    4,  // hasbit index offset
    PROTOBUF_FIELD_OFFSET(::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest, _impl_.email_),
    0,
    0x081,  // bitmap
    PROTOBUF_FIELD_OFFSET(::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse_DataEntry_DoNotUse, _impl_._has_bits_),
    5,  // hasbit index offset
    PROTOBUF_FIELD_OFFSET(::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse_DataEntry_DoNotUse, _impl_.key_),
    PROTOBUF_FIELD_OFFSET(::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse_DataEntry_DoNotUse, _impl_.value_),
    0,
    1,
    0x081,  // bitmap
    PROTOBUF_FIELD_OFFSET(::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse, _impl_._has_bits_),
    6,  // hasbit index offset
    PROTOBUF_FIELD_OFFSET(::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse, _impl_.code_),
    PROTOBUF_FIELD_OFFSET(::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse, _impl_.message_),
    PROTOBUF_FIELD_OFFSET(::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse, _impl_.data_),
    1,
    0,
    2,
};

static const ::_pbi::MigrationSchema schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
    {0, sizeof(::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest)},
    {5, sizeof(::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse_DataEntry_DoNotUse)},
    {12, sizeof(::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::KBchulan::ChatRoom::VerifyCode::_VerifyCodeRequest_default_instance_._instance,
    &::KBchulan::ChatRoom::VerifyCode::_VerifyCodeResponse_DataEntry_DoNotUse_default_instance_._instance,
    &::KBchulan::ChatRoom::VerifyCode::_VerifyCodeResponse_default_instance_._instance,
};
const char descriptor_table_protodef_verify_5fcode_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021verify_code.proto\022\034KBchulan.ChatRoom.V"
    "erifyCode\"\"\n\021VerifyCodeRequest\022\r\n\005email\030"
    "\001 \001(\t\"\252\001\n\022VerifyCodeResponse\022\014\n\004code\030\001 \001"
    "(\005\022\017\n\007message\030\002 \001(\t\022H\n\004data\030\003 \003(\0132:.KBch"
    "ulan.ChatRoom.VerifyCode.VerifyCodeRespo"
    "nse.DataEntry\032+\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022"
    "\r\n\005value\030\002 \001(\t:\0028\0012\204\001\n\021VerifyCodeService"
    "\022o\n\nVerifyCode\022/.KBchulan.ChatRoom.Verif"
    "yCode.VerifyCodeRequest\0320.KBchulan.ChatR"
    "oom.VerifyCode.VerifyCodeResponseb\006proto"
    "3"};
static ::absl::once_flag descriptor_table_verify_5fcode_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_verify_5fcode_2eproto = {
    false,
    false,
    401,
    descriptor_table_protodef_verify_5fcode_2eproto,
    "verify_code.proto",
    &descriptor_table_verify_5fcode_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_verify_5fcode_2eproto::offsets,
    file_level_enum_descriptors_verify_5fcode_2eproto,
    file_level_service_descriptors_verify_5fcode_2eproto,
};
namespace KBchulan
{
namespace ChatRoom
{
namespace VerifyCode
{
// ===================================================================

class VerifyCodeRequest::_Internal
{
public:
  using HasBits = decltype(::std::declval<VerifyCodeRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset = 8 * PROTOBUF_FIELD_OFFSET(VerifyCodeRequest, _impl_._has_bits_);
};

VerifyCodeRequest::VerifyCodeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VerifyCodeRequest_class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
}
PROTOBUF_NDEBUG_INLINE VerifyCodeRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& from_msg)
    : _has_bits_{from._has_bits_}, _cached_size_{0}, email_(arena, from.email_)
{
}

VerifyCodeRequest::VerifyCodeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VerifyCodeRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VerifyCodeRequest_class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
  VerifyCodeRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
}
PROTOBUF_NDEBUG_INLINE VerifyCodeRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : _cached_size_{0}, email_(arena)
{
}

inline void VerifyCodeRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena)
{
  new (&_impl_) Impl_(internal_visibility(), arena);
}
VerifyCodeRequest::~VerifyCodeRequest()
{
  // @@protoc_insertion_point(destructor:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
  SharedDtor(*this);
}
inline void VerifyCodeRequest::SharedDtor(MessageLite& self)
{
  VerifyCodeRequest& this_ = static_cast<VerifyCodeRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
  {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.email_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL VerifyCodeRequest::PlacementNew_(const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
                                                               ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
{
  return ::new (mem) VerifyCodeRequest(arena);
}
constexpr auto VerifyCodeRequest::InternalNewImpl_()
{
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VerifyCodeRequest), alignof(VerifyCodeRequest));
}
constexpr auto VerifyCodeRequest::InternalGenerateClassData_()
{
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_VerifyCodeRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &VerifyCodeRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<VerifyCodeRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VerifyCodeRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<VerifyCodeRequest>(),
          &VerifyCodeRequest::ByteSizeLong,
          &VerifyCodeRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VerifyCodeRequest, _impl_._cached_size_),
          false,
      },
      &VerifyCodeRequest::kDescriptorMethods,
      &descriptor_table_verify_5fcode_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    VerifyCodeRequest_class_data_ = VerifyCodeRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VerifyCodeRequest::GetClassData() const
{
  ::google::protobuf::internal::PrefetchToLocalCache(&VerifyCodeRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VerifyCodeRequest_class_data_.tc_table);
  return VerifyCodeRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<0, 1, 0, 60, 2>
    VerifyCodeRequest::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(VerifyCodeRequest, _impl_._has_bits_),
            0,  // no _extensions_
            1,
            0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967294,  // skipmap
            offsetof(decltype(_table_), field_entries),
            1,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            VerifyCodeRequest_class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // string email = 1;
            {::_pbi::TcParser::FastUS1, {10, 0, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeRequest, _impl_.email_)}},
        }},
        {{65535, 65535}},
        {{
            // string email = 1;
            {PROTOBUF_FIELD_OFFSET(VerifyCodeRequest, _impl_.email_), _Internal::kHasBitsOffset + 0, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
        }},
        // no aux_entries
        {{"\56\5\0\0\0\0\0\0"
          "KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest"
          "email"}},
    };
PROTOBUF_NOINLINE void VerifyCodeRequest::Clear()
{
  // @@protoc_insertion_point(message_clear_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U))
  {
    _impl_.email_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL
VerifyCodeRequest::_InternalSerialize(const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
                                      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream)
{
  const VerifyCodeRequest& this_ = static_cast<const VerifyCodeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VerifyCodeRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target, ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const
{
  const VerifyCodeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
  {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string email = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U))
  {
    if (!this_._internal_email().empty())
    {
      const ::std::string& _s = this_._internal_email();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest.email");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
  {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VerifyCodeRequest::ByteSizeLong(const MessageLite& base)
{
  const VerifyCodeRequest& this_ = static_cast<const VerifyCodeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VerifyCodeRequest::ByteSizeLong() const
{
  const VerifyCodeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  {
    // string email = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U))
    {
      if (!this_._internal_email().empty())
      {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(this_._internal_email());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size, &this_._impl_._cached_size_);
}

void VerifyCodeRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                                  const ::google::protobuf::MessageLite& from_msg)
{
  auto* const _this = static_cast<VerifyCodeRequest*>(&to_msg);
  auto& from = static_cast<const VerifyCodeRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
  {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U))
  {
    if (!from._internal_email().empty())
    {
      _this->_internal_set_email(from._internal_email());
    }
    else
    {
      if (_this->_impl_.email_.IsDefault())
      {
        _this->_internal_set_email("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VerifyCodeRequest::CopyFrom(const VerifyCodeRequest& from)
{
  // @@protoc_insertion_point(class_specific_copy_from_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VerifyCodeRequest::InternalSwap(VerifyCodeRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other)
{
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
}

::google::protobuf::Metadata VerifyCodeRequest::GetMetadata() const
{
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
VerifyCodeResponse_DataEntry_DoNotUse::VerifyCodeResponse_DataEntry_DoNotUse()
    : SuperType(VerifyCodeResponse_DataEntry_DoNotUse_class_data_.base())
{
}
VerifyCodeResponse_DataEntry_DoNotUse::VerifyCodeResponse_DataEntry_DoNotUse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, VerifyCodeResponse_DataEntry_DoNotUse_class_data_.base())
{
}
#else   // PROTOBUF_CUSTOM_VTABLE
VerifyCodeResponse_DataEntry_DoNotUse::VerifyCodeResponse_DataEntry_DoNotUse() : SuperType()
{
}
VerifyCodeResponse_DataEntry_DoNotUse::VerifyCodeResponse_DataEntry_DoNotUse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena)
{
}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL VerifyCodeResponse_DataEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem, ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
{
  return ::new (mem) VerifyCodeResponse_DataEntry_DoNotUse(arena);
}
constexpr auto VerifyCodeResponse_DataEntry_DoNotUse::InternalNewImpl_()
{
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VerifyCodeResponse_DataEntry_DoNotUse),
                                                                alignof(VerifyCodeResponse_DataEntry_DoNotUse));
}
constexpr auto VerifyCodeResponse_DataEntry_DoNotUse::InternalGenerateClassData_()
{
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_VerifyCodeResponse_DataEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &VerifyCodeResponse_DataEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<VerifyCodeResponse_DataEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VerifyCodeResponse_DataEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&VerifyCodeResponse_DataEntry_DoNotUse::ClearImpl),
          ::google::protobuf::Message::ByteSizeLongImpl,
          ::google::protobuf::Message::_InternalSerializeImpl,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VerifyCodeResponse_DataEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &VerifyCodeResponse_DataEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_verify_5fcode_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    VerifyCodeResponse_DataEntry_DoNotUse_class_data_ =
        VerifyCodeResponse_DataEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VerifyCodeResponse_DataEntry_DoNotUse::GetClassData() const
{
  ::google::protobuf::internal::PrefetchToLocalCache(&VerifyCodeResponse_DataEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VerifyCodeResponse_DataEntry_DoNotUse_class_data_.tc_table);
  return VerifyCodeResponse_DataEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<1, 2, 0, 74, 2>
    VerifyCodeResponse_DataEntry_DoNotUse::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(VerifyCodeResponse_DataEntry_DoNotUse, _impl_._has_bits_),
            0,  // no _extensions_
            2,
            8,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967292,  // skipmap
            offsetof(decltype(_table_), field_entries),
            2,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            VerifyCodeResponse_DataEntry_DoNotUse_class_data_.base(),
            nullptr,                                      // post_loop_handler
            ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse_DataEntry_DoNotUse>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // string value = 2;
            {::_pbi::TcParser::FastUS1,
             {18, 1, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeResponse_DataEntry_DoNotUse, _impl_.value_)}},
            // string key = 1;
            {::_pbi::TcParser::FastUS1,
             {10, 0, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeResponse_DataEntry_DoNotUse, _impl_.key_)}},
        }},
        {{65535, 65535}},
        {{
            // string key = 1;
            {PROTOBUF_FIELD_OFFSET(VerifyCodeResponse_DataEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0,
             0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
            // string value = 2;
            {PROTOBUF_FIELD_OFFSET(VerifyCodeResponse_DataEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1,
             0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
        }},
        // no aux_entries
        {{"\71\3\5\0\0\0\0\0"
          "KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.DataEntry"
          "key"
          "value"}},
    };
// ===================================================================

class VerifyCodeResponse::_Internal
{
public:
  using HasBits = decltype(::std::declval<VerifyCodeResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset = 8 * PROTOBUF_FIELD_OFFSET(VerifyCodeResponse, _impl_._has_bits_);
};

VerifyCodeResponse::VerifyCodeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VerifyCodeResponse_class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
}
PROTOBUF_NDEBUG_INLINE VerifyCodeResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse& from_msg)
    : _has_bits_{from._has_bits_},
      _cached_size_{0},
      message_(arena, from.message_),
      data_{visibility, arena, from.data_}
{
}

VerifyCodeResponse::VerifyCodeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
                                       const VerifyCodeResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VerifyCodeResponse_class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
  VerifyCodeResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.code_ = from._impl_.code_;

  // @@protoc_insertion_point(copy_constructor:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
}
PROTOBUF_NDEBUG_INLINE VerifyCodeResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : _cached_size_{0}, message_(arena), data_{visibility, arena}
{
}

inline void VerifyCodeResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena)
{
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.code_ = {};
}
VerifyCodeResponse::~VerifyCodeResponse()
{
  // @@protoc_insertion_point(destructor:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
  SharedDtor(*this);
}
inline void VerifyCodeResponse::SharedDtor(MessageLite& self)
{
  VerifyCodeResponse& this_ = static_cast<VerifyCodeResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
  {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL VerifyCodeResponse::PlacementNew_(const void* PROTOBUF_NONNULL,
                                                                void* PROTOBUF_NONNULL mem,
                                                                ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
{
  return ::new (mem) VerifyCodeResponse(arena);
}
constexpr auto VerifyCodeResponse::InternalNewImpl_()
{
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(VerifyCodeResponse, _impl_.data_) +
          decltype(VerifyCodeResponse::_impl_.data_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value())
  {
    return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VerifyCodeResponse),
                                                                  alignof(VerifyCodeResponse), *arena_bits);
  }
  else
  {
    return ::google::protobuf::internal::MessageCreator(&VerifyCodeResponse::PlacementNew_, sizeof(VerifyCodeResponse),
                                                        alignof(VerifyCodeResponse));
  }
}
constexpr auto VerifyCodeResponse::InternalGenerateClassData_()
{
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_VerifyCodeResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &VerifyCodeResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<VerifyCodeResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VerifyCodeResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<VerifyCodeResponse>(),
          &VerifyCodeResponse::ByteSizeLong,
          &VerifyCodeResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VerifyCodeResponse, _impl_._cached_size_),
          false,
      },
      &VerifyCodeResponse::kDescriptorMethods,
      &descriptor_table_verify_5fcode_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    VerifyCodeResponse_class_data_ = VerifyCodeResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VerifyCodeResponse::GetClassData() const
{
  ::google::protobuf::internal::PrefetchToLocalCache(&VerifyCodeResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VerifyCodeResponse_class_data_.tc_table);
  return VerifyCodeResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<1, 3, 1, 67, 2>
    VerifyCodeResponse::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(VerifyCodeResponse, _impl_._has_bits_),
            0,  // no _extensions_
            3,
            8,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967288,  // skipmap
            offsetof(decltype(_table_), field_entries),
            3,  // num_field_entries
            1,  // num_aux_entries
            offsetof(decltype(_table_), aux_entries),
            VerifyCodeResponse_class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // string message = 2;
            {::_pbi::TcParser::FastUS1, {18, 0, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeResponse, _impl_.message_)}},
            // int32 code = 1;
            {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VerifyCodeResponse, _impl_.code_), 1>(),
             {8, 1, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeResponse, _impl_.code_)}},
        }},
        {{65535, 65535}},
        {{
            // int32 code = 1;
            {PROTOBUF_FIELD_OFFSET(VerifyCodeResponse, _impl_.code_), _Internal::kHasBitsOffset + 1, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
            // string message = 2;
            {PROTOBUF_FIELD_OFFSET(VerifyCodeResponse, _impl_.message_), _Internal::kHasBitsOffset + 0, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
            // map<string, string> data = 3;
            {PROTOBUF_FIELD_OFFSET(VerifyCodeResponse, _impl_.data_), _Internal::kHasBitsOffset + 2, 0,
             (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
        }},
        {{
            {::_pbi::TcParser::GetMapAuxInfo(1, 0, 9, 9, 0)},
        }},
        {{"\57\0\7\4\0\0\0\0"
          "KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse"
          "message"
          "data"}},
    };
PROTOBUF_NOINLINE void VerifyCodeResponse::Clear()
{
  // @@protoc_insertion_point(message_clear_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U))
  {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U))
  {
    _impl_.code_ = 0;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U))
    {
      _impl_.data_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL
VerifyCodeResponse::_InternalSerialize(const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
                                       ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream)
{
  const VerifyCodeResponse& this_ = static_cast<const VerifyCodeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VerifyCodeResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target, ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const
{
  const VerifyCodeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
  {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 code = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U))
  {
    if (this_._internal_code() != 0)
    {
      target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
          stream, this_._internal_code(), target);
    }
  }

  // string message = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U))
  {
    if (!this_._internal_message().empty())
    {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.message");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // map<string, string> data = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U))
  {
    if (!this_._internal_data().empty())
    {
      using MapType = ::google::protobuf::Map<::std::string, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::std::string, _pbi::WireFormatLite::TYPE_STRING,
                                             _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_data();

      if (stream->IsSerializationDeterministic() && field.size() > 1)
      {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field))
        {
          target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
              ::google::protobuf::internal::WireFormatLite::SERIALIZE,
              "KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.data");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
              ::google::protobuf::internal::WireFormatLite::SERIALIZE,
              "KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.data");
        }
      }
      else
      {
        for (const auto& entry : field)
        {
          target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
              ::google::protobuf::internal::WireFormatLite::SERIALIZE,
              "KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.data");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
              ::google::protobuf::internal::WireFormatLite::SERIALIZE,
              "KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse.data");
        }
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
  {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VerifyCodeResponse::ByteSizeLong(const MessageLite& base)
{
  const VerifyCodeResponse& this_ = static_cast<const VerifyCodeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VerifyCodeResponse::ByteSizeLong() const
{
  const VerifyCodeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U))
  {
    // string message = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U))
    {
      if (!this_._internal_message().empty())
      {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(this_._internal_message());
      }
    }
    // int32 code = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U))
    {
      if (this_._internal_code() != 0)
      {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this_._internal_code());
      }
    }
    // map<string, string> data = 3;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U))
    {
      total_size += 1 * ::google::protobuf::internal::FromIntSize(this_._internal_data_size());
      for (const auto& entry : this_._internal_data())
      {
        total_size += _pbi::MapEntryFuncs<::std::string, ::std::string, _pbi::WireFormatLite::TYPE_STRING,
                                          _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size, &this_._impl_._cached_size_);
}

void VerifyCodeResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                                   const ::google::protobuf::MessageLite& from_msg)
{
  auto* const _this = static_cast<VerifyCodeResponse*>(&to_msg);
  auto& from = static_cast<const VerifyCodeResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
  {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U))
  {
    if (CheckHasBit(cached_has_bits, 0x00000001U))
    {
      if (!from._internal_message().empty())
      {
        _this->_internal_set_message(from._internal_message());
      }
      else
      {
        if (_this->_impl_.message_.IsDefault())
        {
          _this->_internal_set_message("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U))
    {
      if (from._internal_code() != 0)
      {
        _this->_impl_.code_ = from._impl_.code_;
      }
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U))
    {
      _this->_impl_.data_.MergeFrom(from._impl_.data_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VerifyCodeResponse::CopyFrom(const VerifyCodeResponse& from)
{
  // @@protoc_insertion_point(class_specific_copy_from_start:KBchulan.ChatRoom.VerifyCode.VerifyCodeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VerifyCodeResponse::InternalSwap(VerifyCodeResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other)
{
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.code_, other->_impl_.code_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::google::protobuf::Metadata VerifyCodeResponse::GetMetadata() const
{
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace VerifyCode
}  // namespace ChatRoom
}  // namespace KBchulan
namespace google
{
namespace protobuf
{
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type _static_init2_ [[maybe_unused]] =
    (::_pbi::AddDescriptors(&descriptor_table_verify_5fcode_2eproto), ::std::false_type{});
#include "google/protobuf/port_undef.inc"
