// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: verify_code.proto

#include "verify_code.grpc.pb.h"

#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/server_context.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/support/sync_stream.h>

#include <functional>
#include <grpcpp/ports_def.inc>

#include "verify_code.pb.h"
namespace KBchulan
{
namespace ChatRoom
{
namespace VerifyCode
{

static const char* VerifyCodeService_method_names[] = {
    "/KBchulan.ChatRoom.VerifyCode.VerifyCodeService/VerifyCode",
};

std::unique_ptr<VerifyCodeService::Stub> VerifyCodeService::NewStub(
    const std::shared_ptr<::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
{
  (void)options;
  std::unique_ptr<VerifyCodeService::Stub> stub(new VerifyCodeService::Stub(channel, options));
  return stub;
}

VerifyCodeService::Stub::Stub(const std::shared_ptr<::grpc::ChannelInterface>& channel,
                              const ::grpc::StubOptions& options)
    : channel_(channel),
      rpcmethod_VerifyCode_(VerifyCodeService_method_names[0], options.suffix_for_stats(),
                            ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
{
}

::grpc::Status VerifyCodeService::Stub::VerifyCode(::grpc::ClientContext* context,
                                                   const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                                                   ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response)
{
  return ::grpc::internal::BlockingUnaryCall<::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
                                             ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse,
                                             ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
      channel_.get(), rpcmethod_VerifyCode_, context, request, response);
}

void VerifyCodeService::Stub::async::VerifyCode(::grpc::ClientContext* context,
                                                const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
                                                ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response,
                                                std::function<void(::grpc::Status)> f)
{
  ::grpc::internal::CallbackUnaryCall<::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
                                      ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse,
                                      ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
      stub_->channel_.get(), stub_->rpcmethod_VerifyCode_, context, request, response, std::move(f));
}

void VerifyCodeService::Stub::async::VerifyCode(::grpc::ClientContext* context,
                                                const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
                                                ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response,
                                                ::grpc::ClientUnaryReactor* reactor)
{
  ::grpc::internal::ClientCallbackUnaryFactory::Create<::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
      stub_->channel_.get(), stub_->rpcmethod_VerifyCode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>*
VerifyCodeService::Stub::PrepareAsyncVerifyCodeRaw(::grpc::ClientContext* context,
                                                   const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                                                   ::grpc::CompletionQueue* cq)
{
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
      ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse, ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
      ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VerifyCode_, context,
                                                                    request);
}

::grpc::ClientAsyncResponseReader<::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse>*
VerifyCodeService::Stub::AsyncVerifyCodeRaw(::grpc::ClientContext* context,
                                            const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest& request,
                                            ::grpc::CompletionQueue* cq)
{
  auto* result = this->PrepareAsyncVerifyCodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

VerifyCodeService::Service::Service()
{
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VerifyCodeService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler<VerifyCodeService::Service,
                                             ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest,
                                             ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse,
                                             ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VerifyCodeService::Service* service, ::grpc::ServerContext* ctx,
             const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* req,
             ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* resp)
          { return service->VerifyCode(ctx, req, resp); },
          this)));
}

VerifyCodeService::Service::~Service()
{
}

::grpc::Status VerifyCodeService::Service::VerifyCode(
    ::grpc::ServerContext* context, const ::KBchulan::ChatRoom::VerifyCode::VerifyCodeRequest* request,
    ::KBchulan::ChatRoom::VerifyCode::VerifyCodeResponse* response)
{
  (void)context;
  (void)request;
  (void)response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

}  // namespace VerifyCode
}  // namespace ChatRoom
}  // namespace KBchulan
#include <grpcpp/ports_undef.inc>
