@baseUrl = http://localhost:10001

### GET 请求测试
GET {{baseUrl}}/demo/get-test?name=chulan&age=18 HTTP/1.1

### POST 请求测试
POST {{baseUrl}}/demo/post-test HTTP/1.1
Content-Type: application/json

{
  "title": "Test Title",
  "content": "Test Content"
}

### PUT 请求测试
PUT {{baseUrl}}/demo/put-test HTTP/1.1
Content-Type: application/json

{
  "title": "Test Title",
  "content": "Test Content"
}

### DELETE 请求测试
DELETE {{baseUrl}}/demo/delete-test?id=123 HTTP/1.1