@baseUrl = http://localhost:8000/api/v1

### 健康检查
GET {{baseUrl}}/health-check HTTP/1.1

### 发送验证码
POST {{baseUrl}}/user/send-code HTTP/1.1
Content-Type: application/json

{
  "email": "2262317520@qq.com",
  "purpose": 1
}

### 用户注册
POST {{baseUrl}}/user/register HTTP/1.1
Content-Type: application/json

{
  "nickname": "chulan",
  "email": "2262317520@qq.com",
  "password": "whx051021",
  "confirm_password": "whx051021",
  "verify_code": "89140e",
  "purpose": 1
}

### 重置密码
POST {{baseUrl}}/user/reset HTTP/1.1
Content-Type: application/json

{
  "email": "2262317520@qq.com",
  "password": "whx051021",
  "confirm_password": "whx051021",
  "verify_code": "cd91e6",
  "purpose": 2
}

### 用户登录
POST {{baseUrl}}/user/login HTTP/1.1
Content-Type: application/json

{
  "user": "2262317520@qq.com",  // 可以是 email 或者 nickname
  "password": "whx051021"
}